services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PSB\PsbFoundation\:
    resource: '../Classes/*'

  PSB\PsbFoundation\Service\Configuration\RegistrationService:
    public: true

  PSB\PsbFoundation\Service\Configuration\TcaService:
    public: true

  PSB\PsbFoundation\Service\ExtensionInformationService:
    public: true

  PSB\PsbFoundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true

  PSB\PsbFoundation\Service\LocalizationService:
    public: true

  PSB\PsbFoundation\Service\ObjectService:
    public: true

  PSB\PsbFoundation\Service\TypoScriptProviderService:
    public: true
