services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  PSBits\Foundation\:
    resource: '../Classes/*'

  PSBits\Foundation\EventListener\CacheConfigurationBuilder:
    tags:
      - identifier: 'foundation_cacheConfigurationBuilder'
        name: event.listener

  PSBits\Foundation\EventListener\DatabaseEnricher:
    tags:
      - identifier: 'foundation_databaseEnricher'
        name: event.listener

  PSBits\Foundation\Service\Configuration\ModuleService:
    public: true

  PSBits\Foundation\Service\Configuration\PageTypeService:
    public: true

  PSBits\Foundation\Service\Configuration\PluginService:
    public: true

  PSBits\Foundation\Service\Configuration\TcaService:
    public: true

  PSBits\Foundation\Service\ExtensionInformationService:
    public: true

  PSBits\Foundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true

  PSBits\Foundation\Service\LocalizationService:
    public: true

  PSBits\Foundation\Service\ObjectService:
    public: true

  PSBits\Foundation\Service\TypoScriptProviderService:
    public: true
