services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PSB\PsbFoundation\:
    resource: '../Classes/*'

  PSB\PsbFoundation\EventListener\DatabaseEnricher:
    tags:
      - name: event.listener
        identifier: 'psbFoundation_databaseEnricher'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  PSB\PsbFoundation\Service\Configuration\ModuleService:
    public: true

  PSB\PsbFoundation\Service\Configuration\PageTypeService:
    public: true

  PSB\PsbFoundation\Service\Configuration\PluginService:
    public: true

  PSB\PsbFoundation\Service\Configuration\TcaService:
    public: true

  PSB\PsbFoundation\Service\ExtensionInformationService:
    public: true

  PSB\PsbFoundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true

  PSB\PsbFoundation\Service\LocalizationService:
    public: true

  PSB\PsbFoundation\Service\ObjectService:
    public: true

  PSB\PsbFoundation\Service\TypoScriptProviderService:
    public: true
