services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  PSB\PsbFoundation\:
    resource: '../Classes/*'

  PSB\PsbFoundation\EventListener\CacheConfigurationBuilder:
    tags:
      - identifier: 'psbFoundation_cacheConfigurationBuilder'
        name: event.listener

  PSB\PsbFoundation\EventListener\DatabaseEnricher:
    tags:
      - identifier: 'psbFoundation_databaseEnricher'
        name: event.listener

  PSB\PsbFoundation\Service\Configuration\ModuleService:
    public: true

  PSB\PsbFoundation\Service\Configuration\PageTypeService:
    public: true

  PSB\PsbFoundation\Service\Configuration\PluginService:
    public: true

  PSB\PsbFoundation\Service\Configuration\TcaService:
    public: true

  PSB\PsbFoundation\Service\ExtensionInformationService:
    public: true

  PSB\PsbFoundation\Service\GlobalVariableProviders\SiteConfigurationProvider:
    public: true

  PSB\PsbFoundation\Service\LocalizationService:
    public: true

  PSB\PsbFoundation\Service\ObjectService:
    public: true

  PSB\PsbFoundation\Service\TypoScriptProviderService:
    public: true
